swagger: "2.0"
info:
  title: NsFocus Shop
  description: Demo Project Using SSM
  version: 1.0.0
  contact:
    email: "16604643+kmahyyg@users.noreply.github.com"
  license:
    name: "GNU Affero General Public License v3.0"
    url: "https://www.gnu.org/licenses/agpl-3.0.en.html"
host: eshop.docker.test
schemes:
  - http
basePath: /api
tags:
  - name: "user"
    description: "Operations about user"
  - name: "cart"
    description: "Operations about users' cart"
  - name: "shop"
    description: "Operations about items on sale"
  - name: "order"
    description: "Operations about orders"
securityDefinitions:
  sessionID:
    type: apiKey
    name: Authorization
    description: JWT Token with bearer authentication.
    in: header
consumes:
  - application/json
produces:
  - applicaiton/json
definitions:
  Order:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      status:
        type: "integer"
        format: "int32"
        enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
        description: "0=失效，1=创建，2=等待付款，3=等待发货，4=等待人工介入，5=订单完毕"
      items:
        type: "string"
        format: "[]Item"
      finalprice:
        type: "number"
        format: "float"
      generateTime:
        type: "integer"
        format: "int64"
        description: "Unix TimeStamp with UTC timezone"
      paidTime:
        type: "integer"
        format: "int64"
        description: "Unix TimeStamp with UTC timezone"
      doneTime:
        type: "integer"
        format: "int64"
        description: "Unix Timestamp with UTC timezone"
      refundTime:
        type: "integer"
        format: "int64"
        description: "Unix Timestamp with UTC timezone"
      relatedUser:
        type: "string"
        format: "uuid"
      relatedPayment:
        type: "string"
        format: "uuid"
      relatedDelivery:
        type: "string"
        format: "int"
  ItemCategory:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
  Item:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      category:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      price:
        type: "number"
        format: "float"
      status:
        type: "integer"
        format: "int32"
        enum:
          - 0
          - 1
          - 2
        description: "0=创建完毕等待上架，1=已上架，2=已下架"
      image:
        type: "string"
        format: "url"
        description: "Relative Path of Image"
      desc:
        type: "string"
        description: "Description for item"
      belongsto:
        type: "string"
        format: "uuid"
  Cart:
    type: "object"
    properties:
      user:
        type: "string"
        format: "uuid"
      items:
        type: "string"
        format: "[]{item:quantity}"
  User:
    type: "object"
    properties:
      name:
        type: "string"
      phone:
        type: "integer"
        format: "int64"
      id:
        type: "string"
        format: "uuid"
      password:
        type: "string"
        format: "password"
      role:
        type: "string"
        format: "uuid"
      avatar:
        type: "string"
        format: "url"
      preferredPay:
        type: "string"
        format: "uuid"
      preferredDelivery:
        type: "string"
        format: "uuid"
      address:
        type: "string"
        format: "string"
  Payment:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      connected_to:
        type: "string"
        enum:
          - Alipay
          - WC_Pay
          - PY_Pay
  Delivery:
    type: "object"
    properties:
      method:
        type: "string"
      id:
        type: "integer"
        format: "int32"
      cost:
        type: "number"
        format: "float"
  Role:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      access:
        type: "string"
        enum:
          - "admin"
          - "customer"
          - "guest"
          - "shop"
          - "service_shop"
          - "service_platform"
paths:
  /shop:

  /user:
  /order:
  /system:
  
